name = "learn1-478799018"
compatibility_date = "2025-12-31"
main = "_worker.js"

[env.vars]
SUB_PATH = "https://learn1.478799018.workers.dev/hello"
TXT_URL = "https://raw.githubusercontent.com/ImLTHQ/edgetunnel/main/output.txt"
NAT64 = "2a02:898:146:64::"
DOH = "1.1.1.1"
PROXY_IP = "proxyip.cmliussss.net"
FAKE_WEB = "https://baidu.com"
